-- =============================================================================
-- COGS PERHITUNGAN — Skema Database
--
-- SKEMA LENGKAP (semua tabel):
--   → database/mysql_schema_full.sql
--
-- PATCH INCREMENTAL (jika DB sudah ada):
--   → database/unify_hpp_cogs.sql     (HPP = COGS)
--   → database/add_admin_hr.sql       (Admin + HR)
--   → database/pos_module.sql         (Modul POS)
--
-- DISARANKAN:
--   php artisan migrate --force
--
-- Database: cogs_perhitungan (lihat .env)
-- =============================================================================
